### ISSUE TITLE
Update icon or icon colour to match other SS4 icons in the CMS

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-taxonomy#42]
![image](https://user-images.githubusercontent.com/14869519/34085089-e3f0028a-e3ef-11e7-9cdc-015c08ce1f49.png)

This could either be a font icon from core, or be updated to the same colour as the other icons

**Comment by robbieaverill** [comment]
cc @sachajudd @clarkepaul - should we just recolour the image for now, since there's no font icon for a tag/label?

**Comment by clarkepaul** [comment]
Yup could colour it, and in the meantime I'll add a tag icon (or is the better one for taxonomies?) to the CMS set. There will probably be others which also need adding so just keep letting us know about them.

**Comment by clarkepaul** [comment]
I've added these two icons to the CMS design set but haven't made a PR to get then into core yet.
![image](https://user-images.githubusercontent.com/555033/34085484-79da2fea-e3f6-11e7-892d-fdcb8395d907.png)
I can provide guidance if you want to make the PR otherwise it'll happen automatically when we make other updates to the font.

**Comment by robbieaverill** [comment]
Great. No rush, we'll use an image for now.

**Comment by sachajudd** [comment]
I can make a PR to get then into core this week 👍

**Comment by raissanorth** [comment]
Thanks team! I made a PR to include the tags: https://github.com/silverstripe/silverstripe-admin/pull/408

**Comment by sachajudd** [comment]
Awesome work! @raissanorth
